### ISSUE TITLE
ERROR: sanic-sse 0.2.7 has requirement sanic<0.8.0,>=0.7.0

### ISSUE THREAD

**Issue by vassilis-panos** [inn0kenty/sanic_sse#3]
Hi,
Getting the following error when trying to install using pip::
ERROR: sanic-sse 0.2.7 has requirement sanic<0.8.0,>=0.7.0, but you'll have sanic 19.12.2 which is incompatible.

Python 3.8

**Comment by inn0le** [comment]
Thanks! 
This should be fixed in 0.2.8.
