### ISSUE TITLE
FEATURE/IDEA: Multiple tab connections or Multiple browser connections are not allowed with same channel_id

### ISSUE THREAD

**Issue by mdabdulraheem** [inn0kenty/sanic_sse#4]
**DESCRIPTION:**
If a user opens multiple browser tabs or uses the site in multiple browsers, then only the first connection is accepted and all other connections will be rejected.

If user tries to connect with multiple tabs using same channel_id, presently we get response message as _**"Channel_id already in use"**_

There should be a way to allow multiple tab connections across different browsers.

**Comment by inn0le** [comment]
Thanks a lot for participating!

This released in 0.3.1.
